import { type NextPage } from "next";
import Head from "next/head";
import { format, parseISO } from "date-fns";
import { toast } from "react-toastify";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: projects } = api.project.getProjects.useQuery(
    { page: 1, limit: 10 },
    {
      staleTime: 5 * 1000,
      select: (data) => data.projects,
      onError(err) {
        toast(err.message, {
          type: "error",
          position: "top-right"
        });
      },
    }
  );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <section className="bg-white dark:bg-gray-900">
          <div className="container px-6 py-10 mx-auto">
            <h1 className="text-3xl font-semibold text-gray-800 capitalize lg:text-4xl dark:text-white">すべて</h1>

            <div className="grid grid-cols-1 gap-8 mt-8 md:mt-16 md:grid-cols-2">

              {projects?.map((project) => (
                <div key={project.id} className="lg:flex">
                  <img className="object-cover w-full h-56 rounded-lg lg:w-64" src={project.thumbnail} alt={project.name} />

                  <div className="flex flex-col justify-between py-6 lg:mx-6">
                    <a href="#" className="text-xl font-semibold text-gray-800 hover:underline dark:text-white">{project.name}</a>

                    <span className="text-sm text-gray-500 dark:text-gray-300">{format(parseISO(project.createdAt.toISOString()), "PPP")}</span>
                  </div>
                </div>
              ))}

            </div>

          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
